### ISSUE TITLE
Can't get the heex file syntax highlight. 

### ISSUE THREAD

**Issue by iiiyu** [Ritvyk/vscode-heex-html#1]
Hi, Ritvyk
I installed the extension. But my vscode can't show syntax highlighting. 

![CleanShot 2022-02-06 at 18 31 40@2x](https://user-images.githubusercontent.com/1130144/152668908-d1841144-4e32-438f-8a59-8013602730f4.png)

What else do I need to do besides installing it?

This is my vscode version:
<img width="285" alt="CleanShot 2022-02-06 at 18 30 36@2x" src="https://user-images.githubusercontent.com/1130144/152668888-508b76b6-bcad-442e-9aa7-eadced95bb18.png">
Version: 1.64.0 (Universal)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

I installed Hexx HTML v0.0.5

Could you give me a hand?

Ewan

**Comment by Ritvyk** [comment]
@iiiyu Check whether is there any other extension causing the extension break.
or else you can go through these steps to see if it's working fine :

1. Install Monokai Dimmed , Uninstall any other phoenix highlighting extension for now.
2. Check whether it's installed correctly (Heex-HTML)
3. Create a new file with heex.html extension and reload the VSCode

Let me know if the issue still persists.

> Hi, Ritvyk I installed the extension. But my vscode can't show syntax highlighting.
> 
> ![CleanShot 2022-02-06 at 18 31 40@2x](https://user-images.githubusercontent.com/1130144/152668908-d1841144-4e32-438f-8a59-8013602730f4.png)
> 
> What else do I need to do besides installing it?
> 
> This is my vscode version: <img alt="CleanShot 2022-02-06 at 18 30 36@2x" width="285" src="https://user-images.githubusercontent.com/1130144/152668888-508b76b6-bcad-442e-9aa7-eadced95bb18.png"> Version: 1.64.0 (Universal) Commit: 5554b12acf27056905806867f251c859323ff7e9 Date: 2022-02-03T04:20:17.224Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin arm64 21.2.0
> 
> I installed Hexx HTML v0.0.5
> 
> Could you give me a hand?
> 
> Ewan

**Comment by iiiyu** [comment]
Hi @Ritvyk ,
I uninstalled my all elixir extensions and just install the Heex HTML extension. 
It works.
thanks for your work.

I will try to find which one can't work together.
